### ISSUE TITLE
Not on login page

### ISSUE THREAD

**Issue by jakamoo33** [IwraStudios/Whatsapp-Bot#12]
page load and login.

Not on login page error.
Not on login page error.
Not on login page error.

**Comment by vfxloco** [comment]
**1st** - Option to Solve
In the file `Whatsapp-Bot/WebWhatsappAPI/BaseClass.cs` at Line [174](https://github.com/IwraStudios/Whatsapp-Bot/blob/master/WebWhatsappAPI/BaseClass.cs#L174).
Change this `if(driver.FindElement(By.XPath("//div[@class='qr-wrapper-container']")) != null)`.
For this `if(driver.FindElement(By.XPath("//img[@alt='Scan me!']")) != null)`.

> This error is caused because the function is not finding the `qr-wrapper-container` element in the Login page, to solve you put an existing element in the Login page eg the QRCode itself.

**2nd** - Option to Solve
In the file `Whatsapp-Bot/ModularExample/Program.cs`.
Delete line `50` to line `64`.
This will remove the function that checks the start page. 

> It is not recommended because it will be looking for messages without even being logged in. And it would be a way of "[Workaround](https://en.wikipedia.org/wiki/Workaround)".

**Comment by vfxloco** [comment]
# Bug Fixed
