### ISSUE TITLE
Connected/Disconnected

### ISSUE THREAD

**Issue by eaba** [IwraStudios/Whatsapp-Bot#3]
@IwraStudios one more thing,
WhatsApp web lets you know when the phone is not connected, can this be achieved?
I need to use that to alert users when their phone is not online/disconnected.
Thanks

**Comment by IwraStudios** [comment]
Shouldn't be too hard, I'll add it to the API
takes only an half an hour or so

**Comment by IwraStudios** [comment]
Did it "IsPhoneConnected()" returns a bool, true if the phone is connected

Have not tested it yet, though. So tell me if it doesn't work

The example program has an example in it so you can see how to possibly implement it

**Comment by eaba** [comment]
Okay thanks
Appreciated!!
