### ISSUE TITLE
i'm using selenium with electron whatsapp! from Enricho

### ISSUE THREAD

**Issue by GilbertoBitt** [IwraStudios/Whatsapp-Bot#4]
i trying to implement yours bot with Electron on the Enricho Whastapp app!

**Comment by IwraStudios** [comment]
alright, so what's the issue?

**Comment by GilbertoBitt** [comment]
@IwraStudios nothing just Thank ou about it!  what u done make my life much Easy.

**Comment by IwraStudios** [comment]
your welcome, I hope my project helped you

**Comment by IwraStudios** [comment]
also, if you need any extra documentation or something just make an new issue
