### ISSUE TITLE
Example loop issue

### ISSUE THREAD

**Issue by mvmcjr** [IwraStudios/Whatsapp-Bot#5]
I'm trying to run the FirefoxExample on a W10 x64 Machine, with firefox 55.0.3 and my issue is the firefox marionette window keeps opening and nothing happens.

Here's the console output

![image](https://user-images.githubusercontent.com/4898202/29989955-0cda2858-8f4d-11e7-9bd7-71c798008ee9.png)

**Comment by IwraStudios** [comment]
You are completely right, well that's what I get for not testing my program
I fixed it in the latest commit

Also tell me if you bump into anymore issues

**Comment by mvmcjr** [comment]
I'm going to use this a lot these days, so I might as well send some pull requests. Thank you anyways 👍
