### ISSUE TITLE
Remove packages from project

### ISSUE THREAD

**Issue by mvmcjr** [IwraStudios/Whatsapp-Bot#7]
Remove the packages folder from the github project and use package restoration on the continuous integration build

**Comment by IwraStudios** [comment]
It's fine with me; if you're not planning on doing it I'll try to do it today

**Comment by mvmcjr** [comment]
Well I'm just not used to the continuous integration stuff 😞

**Comment by IwraStudios** [comment]
I did it, it was just adding nuget restore to the pre-build steps
I also removed packages

Thanks for this issue btw, it really decreases the size of the repos
